# Generated by Django 4.1.1 on 2022-09-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="currency",
            field=models.CharField(
                choices=[("rub", "rub"), ("usd", "usd"), ("eur", "eur")],
                default="rub",
                max_length=3,
                verbose_name="Валюта",
            ),
        ),
    ]
